TOKEN = "YOUR_BOT_TOKEN_HERE"

PERMISSION_MAP = {
    "administrator": "administrator",
    "view_channel": "view_channel",
    "manage_channels": "manage_channels",
    "manage_guild": "manage_guild",
    "manage_roles": "manage_roles",
    "manage_webhooks": "manage_webhooks",
    "manage_nicknames": "manage_nicknames",
    "change_nickname": "change_nickname",
    "create_instant_invite": "create_instant_invite",
    "send_messages": "send_messages",
    "send_tts_messages": "send_tts_messages",
    "manage_messages": "manage_messages",
    "embed_links": "embed_links",
    "attach_files": "attach_files",
    "read_message_history": "read_message_history",
    "mention_everyone": "mention_everyone",
    "use_external_emojis": "use_external_emojis",
    "use_external_stickers": "use_external_stickers",
    "add_reactions": "add_reactions",
    "connect": "connect",
    "speak": "speak",
    "mute_members": "mute_members",
    "deafen_members": "deafen_members",
    "move_members": "move_members",
    "use_vad": "use_vad",
    "priority_speaker": "priority_speaker",
    "stream": "stream",
    "use_application_commands": "use_application_commands",
    "request_to_speak": "request_to_speak",
    "manage_threads": "manage_threads",
    "create_public_threads": "create_public_threads",
    "create_private_threads": "create_private_threads",
    "send_messages_in_threads": "send_messages_in_threads",
    "manage_events": "manage_events",
    "moderate_members": "moderate_members",
    "view_audit_log": "view_audit_log",
    "kick_members": "kick_members",
    "ban_members": "ban_members",
}

NAMED_COLORS = {
    "blue": 0x0000ff,
    "blurple": 0x5865f2,
    "brand_green": 0x57f287,
    "brand_red": 0xed4245,
    "dark_blue": 0x00008b,
    "dark_gold": 0x8b8000,
    "dark_gray": 0x545454,
    "dark_green": 0x006400,
    "dark_grey": 0x545454,
    "dark_magenta": 0x8b008b,
    "dark_orange": 0xcc5500,
    "dark_purple": 0x4b0082,
    "dark_red": 0x8b0000,
    "dark_teal": 0x005c5c,
    "default": 0x000000,
    "gold": 0xffd700,
    "green": 0x00ff00,
    "grey": 0x808080,
    "greyple": 0x99aab5,
    "light_gray": 0xb0b0b0,
    "light_grey": 0xb0b0b0,
    "magenta": 0xff00ff,
    "orange": 0xff8000,
    "purple": 0x800080,
    "red": 0xff0000,
    "teal": 0x008080,
    "yellow": 0xffff00,
}
